#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# vim
ln -s ${BASEDIR}/.vimrc ~/.vimrc
ln -s ${BASEDIR}/.vim/ ~/.vim

# git
ln -s ${BASEDIR}/.gitconfig ~/.gitconfig
# emacs
ln -s ${BASEDIR}/.emacs ~/.emacs
ln -s ${BASEDIR}/.emacs.d/ ~/.emacs.d

# install Vundle
#git submodule init
#git submodule update
git submodule foreach git pull origin master
